apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: api
  name: api-developer-role
rules:
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - deployments
  - services
  verbs:
  - "*"