apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  SQL_USER: "c3FsYWRtaW5lV2k0MzI0Cg=="
  SQL_PASSWORD: "UGFzc3dvcmQxMjMK"
  SQL_SERVER: "c3Fsc2VydmVyZXdpNDMyNC5kYXRhYmFzZS53aW5kb3dzLm5ldAo="
  SQL_DBNAME: "bXlkcml2aW5nREIK"