apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi
  namespace: api
  labels:
    app: poi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
      - name: poi
        image: registryewi4324.azurecr.io/tripinsights/poi1
        envFrom:
        - secretRef:
            name: mysecret
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: poi
  labels:
    app: poi
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: poi