apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile
  labels:
    app: userprofile
spec:
  replicas: 3
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      containers:
      - name: userprofile
        image: registryewi4324.azurecr.io/tripinsights/userprofile
        envFrom:
        - secretRef:
            name: mysecret
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: userprofile
  labels:
    app: userprofile
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: userprofile